export const DESTINATIONS_LOADING = 'DESTINATIONS_LOADING';
export const DESTINATIONS_FAILURE = 'DESTINATIONS_FAILURE';
export const DESTINATIONS_LOADED = 'DESTINATIONS_LOADED';
export const DESTINATIONS_PREVIEW_LOADING = 'DESTINATIONS_PREVIEW_LOADING';
export const DESTINATIONS_PREVIEW_FAILURE = 'DESTINATIONS_PREVIEW_FAILURE';
export const DESTINATIONS_PREVIEW_LOADED = 'DESTINATIONS_PREVIEW_LOADED';
