export const DESTINATIONS_LOADING = 'DESTINATIONS_LOADING';
export const DESTINATIONS_FAILURE = 'DESTINATIONS_FAILURE';
export const DESTINATIONS_LOADED = 'DESTINATIONS_LOADED';
export const SINGLE_DESTINATION_LOADING = 'SINGLE_DESTINATION_LOADING';
export const SINGLE_DESTINATION_FAILURE = 'SINGLE_DESTINATION_FAILURE';
export const SINGLE_DESTINATION_LOADED = 'SINGLE_DESTINATION_LOADED';
