export const SET_FILE = 'SET_FILE';
export const SET_FILE_NAME = 'SET_FILE_NAME';
export const FILE_UPLOAD_STARTED = 'FILE_UPLOAD_STARTED';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';
